### PR TITLE
Loadbalance control plane

### PR DESCRIPTION
**Pull request by PurpleBooth**
Currently all incoming connections go to the first control-plane node.
This means that if kured is restarting that node, an API user can
experience downtime. This change loadbalances the incoming requests via
a loadbalancer, meaning the service never appears down.

To facilitate that, we also add a few new labels to resources to allow
for easy identification.

This also means the cluster will be highly available, as we can use the
loadbalancer rather than node IPs for the server ip address.

### CODE REVIEW

**Comment by mysticaltech** [comment]
@PurpleBooth I like this solution because it's clean! And would cost just a tiny bit more than implementing a bastion. Even if we implement the latter, it would be great to keep this possibility.

**Comment by mysticaltech** [comment]
Ok, to merge on my end, would you like to add anything for now @PurpleBooth?

**Review by otavio — APPROVED** [review]

**Comment by PurpleBooth** [comment]
Cool! Nope, go for it, I need to pop out but you can fix the conflicts or I will do it when I am back home in a few hours

**Comment by mysticaltech** [comment]
@PurpleBooth When I try to deploy with the flag on, I get this issue, and it doesn't succeed.

ksnip_20220801-154529

ksnip_20220801-154954

**Pull request merged**
