### PR TITLE
added cilium and calico support for wireguard

### PR DESCRIPTION
**Pull request by aleksasiriski**

### CODE REVIEW

**Comment by aleksasiriski** [comment]
I just followed the official docs on enabling it, didn't test anything. If I may ask, can someone else test this? I've already gone over my monthly budget for Hetzner...

**Comment by mysticaltech** [comment]
@kube-hetzner/core Anyone that can test this would be awesome! Especially the new Calico system that uses helm.

**Comment by aleksasiriski** [comment]
> @kube-hetzner/core Anyone that can test this would be awesome! Especially the new Calico system that uses helm.

I haven't switched to Helm yet, I need to find all the corresponding helm values..

**Comment by mysticaltech** [comment]
@aleksasiriski According to https://github.com/projectcalico/calico/blob/master/calico/getting-started/kubernetes/helm.md, this command will show you the values: `helm show values projectcalico/tigera-operator`.

**Comment by mysticaltech** [comment]
@aleksasiriski What you did here is good, and we will test it in the main PR. So merging for now. 

Changing the Calico to helm seems cumbersome because of the operator and stuff. Maybe in the future, we can make it happen!

**Pull request merged**
