### PR TITLE
Added changes to support firewall rules' description

### PR DESCRIPTION
**Pull request by prabhatnagpal**
Updates main.tf and locals.tf file to add description attribute, which will add support for adding or making changes in the description of firewall rules, instead of empty description of rules on the Hetzner Cloud Firewalls section for the Kubernetes Cluster deployed with terraform.

### CODE REVIEW

**Comment by mysticaltech** [comment]
@prabhatnagpal This PR is perhaps not complete but it seems the way to go. Why did you close it?

**Comment by prabhatnagpal** [comment]
@mysticaltech When I ran the terraform init --upgrade command, I found that it is not reflecting the changes I made in the main.tf and local.tf in the .terraform/modules/kube-hetzner/main.tf
As you guessed it right, PR is not complete, that's why I closed the pull request. I want these changes to get reflected in the .terraform folder also. I need help.

**Comment by mysticaltech** [comment]
@prabhatnagpal Good to hear! Basically, anywhere there are firewall rules, you need to add the description fields. And also when testing, in your kube.tf (that lives in a seperate folder), you have to point your module via the `source` to the repo where you made your changes. And you do not even need to run terraform init again, it will automatically use the module you changed!

**Comment by prabhatnagpal** [comment]
@mysticaltech I took the following steps which made this workflow work actually, that's when I opened PR thinking that I have made it work:-

Step 1. Made changes in the main.tf file and locals.tf file in the root folder adding the description field because those are the only places which firewall rules schema is initialized
**locals.tf**: base_firewall_rules
**main.tf**: resource "hcloud_firewall" "k3s" (content)

Step 2: Created a new folder and copied the kube.tf file (#605 check my kube.tf file) there, made necessary changes and especially added the **extra_firewall_rules** with description of rules

Step 3. Changed directory to new folder and ran the command terraform init --upgrade
If I run terraform plan command right now, the plan doesn't show the "+ description" in the firewall rules section of the output

Step 4. Copied the main.tf and locals.tf from root folder to .terraform/modules/kube-hetzner/
Now, if I run the terraform plan command, it is showing "+ description" in the firewall rules section of the output

Step 5: Ran terraform apply --auto-approve command and it works, the description is successfully added in the rules.

**Comment by mysticaltech** [comment]
@prabhatnagpal If you just pointed the `source` attribute in the kube.tf to your clone of the repo, you would not have to do any of this, all your changes would be reflected file. It will not even copy a local version to .terraform. 

So glad that it works now, if you could fill in the default descriptions, please do, otherwise, I will do it myself before merging.

**Comment by gtmobiservices** [comment]
@mysticaltech Oh, now I got it what you were trying to tell me, the source by default points to the upstream, thus main.tf and locals.tf always came from the main module from terraform registry and if I just pointed to the local path of the root folder, it would have taken the tf files from the root folder itself where I made changes.

And about the default descriptions, meaning filling in the description of all the base_firewall_rules in locals.tf?

**Comment by prabhatnagpal** [comment]
@mysticaltech Oh, now I got it what you were trying to tell me, the source by default points to the upstream, thus main.tf and locals.tf always came from the main module from terraform registry and if I just pointed to the local path of the root folder, it would have taken the tf files from the root folder itself where I made changes.

And about the default descriptions, meaning filling in the description of all the base_firewall_rules in locals.tf?

**Comment by mysticaltech** [comment]
@prabhatnagpal Exactly!

Yes, it would be nice to have them filled.

**Comment by prabhatnagpal** [comment]
@mysticaltech Added the descriptions of all the base firewall rules. Please review.

**Comment by mysticaltech** [comment]
@prabhatnagpal Looking good, thank you! Will merge and deploy ASAP.

**Comment by prabhatnagpal** [comment]
This is my first contribution to a live project. Feeling proud and I am really glad, it was a successful contribution. 😀 Thank you @mysticaltech 🤗

**Comment by mysticaltech** [comment]
Wonderful, very good to hear @prabhatnagpal! 🥳

**Pull request merged**
