### PR TITLE
Add s3 region to docs & move system-upgrade-controller to variables

### LINKED ISSUE #1404: [Bug]: ETCD S3 BackUp doesn't work due to URI issues
### Description

The storage or loading of etcd backups does not work as expected. Using a valid configuration leads to `Failed to record snapshots for cluster: failed to test for existence of bucket <BUCKET_NAME>: 301 Moved Permanently`. 

I was in fact able to make the restore work by adding `--etcd-s3-region=<Region>` to the example script from the `README.md` but the `etcd_s3_backup` input does not support the region (not sure, the field is described as `map(any)`). 

So my guess would be that it is related to the default region

### Kube.tf file

```terraform
locals {
  k3s_token          = local.credentials.K3S_TOKEN
  etcd_version       = "v3.5.9"
  etcd_snapshot_name = <Omitted>
  etcd_s3_endpoint   = "s3.<Region>.amazonaws.com"
  etcd_s3_bucket     = <Omitted>
  etcd_s3_access_key = local.credentials.AWS_ACCESS_KEY_ID
  etcd_s3_secret_key = local.credentials.AWS_SECRET_ACCESS_KEY

  hcloud_token = local.credentials.hetznerCloudToken
}

module "kube-hetzner" {
  providers = {
    hcloud = hcloud
  }
  hcloud_token = var.hcloud_token != "" ? var.hcloud_token : local.hcloud_token


  k3s_token = local.k3s_token

  postinstall_exec = [
    (
      local.etcd_snapshot_name == "" ? "" :
      <<-EOF
      export CLUSTERINIT=$(cat /etc/rancher/k3s/config.yaml | grep -i '"cluster-init": true')
      if [ -n "$CLUSTERINIT" ]; then
        echo indeed this is the first control plane node > /tmp/restorenotes
        k3s server \
          --cluster-reset \
          --etcd-s3 \
          --cluster-reset-restore-path=${local.etcd_snapshot_name} \
          --etcd-s3-endpoint=${local.etcd_s3_endpoint} \
          --etcd-s3-bucket=${local.etcd_s3_bucket} \
          --etcd-s3-region=<Region> \
          --etcd-s3-access-key=${local.etcd_s3_access_key} \
          --etcd-s3-secret-key=${local.etcd_s3_secret_key}
        # renaming the k3s.yaml because it is used as a trigger for further downstream
        # changes. Better to let `k3s server` create it as expected.
        mv /etc/rancher/k3s/k3s.yaml /etc/rancher/k3s/k3s.backup.yaml

        # download etcd/etcdctl for adapting the kubernetes config before starting k3s
        ETCD_VER=${local.etcd_version}
        case "$(uname -m)" in
            aarch64) ETCD_ARCH="arm64" ;;
            x86_64) ETCD_ARCH="amd64" ;;
        esac;
        DOWNLOAD_URL=https://github.com/etcd-io/etcd/releases/download
        rm -f /tmp/etcd-$ETCD_VER-linux-$ETCD_ARCH.tar.gz
        curl -L $DOWNLOAD_URL/$ETCD_VER/etcd-$ETCD_VER-linux-$ETCD_ARCH.tar.gz -o /tmp/etcd-$ETCD_VER-linux-$ETCD_ARCH.tar.gz
        tar xzvf /tmp/etcd-$ETCD_VER-linux-$ETCD_ARCH.tar.gz -C /usr/local/bin --strip-components=1
        rm -f /tmp/etcd-$ETCD_VER-linux-$ETCD_ARCH.tar.gz

        etcd --version
        etcdctl version

        # start etcd server in the background
        nohup etcd --data-dir /var/lib/rancher/k3s/server/db/etcd &
        echo $! > save_pid.txt

        # delete traefik service so that no load-balancer is accidently changed
        etcdctl del /registry/services/specs/traefik/traefik
        etcdctl del /registry/services/endpoints/traefik/traefik

        # delete old nodes (they interfere with load balancer)
        # minions is the old name for "nodes"
        OLD_NODES=$(etcdctl get "" --prefix --keys-only | grep /registry/minions/ | cut -c 19-)
        for NODE in $OLD_NODES; do
          for KEY in $(etcdctl get "" --prefix --keys-only | grep $NODE); do
            etcdctl del $KEY
          done
        done

        kill -9 `cat save_pid.txt`
        rm save_pid.txt
      else
        echo this is not the first control plane node > /tmp/restorenotes
      fi
      EOF
    )
  ]


  source = "kube-hetzner/kube-hetzner/hcloud"

  automatically_upgrade_k3s = false
  automatically_upgrade_os  = false

  ingress_controller = "none"

  enable_cert_manager = false
  ssh_public_key      = <Omitted>
  ssh_private_key     = <Omitted>
  network_region      = "eu-central"

  control_plane_nodepools = [
    {
      name        = "control-plane-fsn1",
      server_type = "cpx11",
      location    = "fsn1",
      labels      = [],
      taints      = [],
      count       = 1,
      backups     = true
    },
  ]

  agent_nodepools = [
    {
      name        = "agent-large-memory",
      server_type = "cx31",
      location    = "fsn1",
      labels      = [],
      taints      = [],
      count       = 4,
      backups     = true
    },
  ]
  
  base_domain = <Omitted>

  etcd_s3_backup = {
    etcd-s3-endpoint   = local.etcd_s3_endpoint
    etcd-s3-access-key = local.credentials.AWS_ACCESS_KEY_ID
    etcd-s3-secret-key = local.credentials.AWS_SECRET_ACCESS_KEY
    etcd-s3-bucket     = local.etcd_s3_bucket
  }

  extra_firewall_rules = [
    {
      description     = "To Allow ArgoCD access to resources via SSH"
      direction       = "out"
      protocol        = "tcp"
      port            = "22"
      source_ips      = []
      destination_ips = ["0.0.0.0/0", "::/0"]
    }
  ]

  dns_servers = [
    "1.1.1.1",
    "8.8.8.8",
    "2606:4700:4700::1111",
  ]
}

provider "hcloud" {
  token = var.hcloud_token != "" ? var.hcloud_token : local.hcloud_token
}

terraform {
  required_version = ">= 1.5.0"
  required_providers {
    hcloud = {
      source  = "hetznercloud/hcloud"
      version = ">= 1.43.0"
    }
  }
}

output "kubeconfig" {
  value     = module.kube-hetzner.kubeconfig
  sensitive = true
}

output "k3s_token" {
  value     = module.kube-hetzner.k3s_token
  sensitive = true
}

variable "hcloud_token" {
  sensitive = true
  default   = ""
}
```

### Screenshots

_No response_

### Platform

Mac

### PR DESCRIPTION
**Pull request by ricristian**

### CODE REVIEW

**Review by mysticaltech — DISMISSED** [review]
Thanks @ricristian! Please could you also update the manifest url to use the latest. You'd do me a huge favor 🙏

https://github.com/kube-hetzner/terraform-hcloud-kube-hetzner/blob/a5a1f7e3129d212afc53031810b1112039d1e93a/locals.tf#L79

**Review by mysticaltech — APPROVED** [review]
🚀

**Comment by maggie44** [comment]
Did the default version go backwards from v0.14.2 to 0.13.4? Any particular reason?

**Comment by ricristian** [comment]
No reason. I believe that I was on a older version of code https://github.com/kube-hetzner/terraform-hcloud-kube-hetzner/pull/1531 here it's the fix

**Comment by mysticaltech** [comment]
Good catch @maggie44! Thanks folks

**Pull request merged**
