### PR TITLE
Fix: Revert back to Kubernetes community autoscaler

### LINKED ISSUE #1505: [Bug]: `docker.io/hetznercloud/cluster-autoscaler` will be removed
### Description

I recently got an email from Hetzner explaining the following:
```
Dear ___

Based on our API monitoring, you are using Kubernetes cluster-autoscaler in your Hetzner Cloud projects. The Hetzner provider in current versions of cluster-autoscaler has a bug and relies on the CX11 server type, which we scheduled for removal from our ordering options on 6 September 2024. To prevent any disruptions for you, we kept the CX11 server type available for your account.

The Kubernetes community has now released new versions of cluster-autoscaler that fix this bug. Please upgrade to the these versions before 4 November 2024.

The following versions include the patches:

    ≥ 1.28.7
    ≥ 1.29.5
    ≥ 1.30.2
    ≥ 1.31.1

We will remove your access to the CX11 server type after 4 November 2024. If you are still using unpatched versions of cluster-autoscaler, they will stop working.

If you were using the alternative container images we provided ([docker.io/hetznercloud/cluster-autoscaler](http://docker.io/hetznercloud/cluster-autoscaler)), please switch back to the images built by the Kubernetes community ([registry.k8s.io/autoscaling/cluster-autoscaler](http://registry.k8s.io/autoscaling/cluster-autoscaler)). We will remove the alternative container images on 19 November 2024.

You can find more information at the following links:

    https://docs.hetzner.cloud/changelog#2024-08-30-bug-cx11-removal-will-break-certain-versions-of-cluster-autoscaler
    https://github.com/kubernetes/autoscaler/issues/7210
    https://docs.hetzner.cloud/changelog#2024-06-06-old-server-types-with-shared-intel-vcpus-are-deprecated

We will be happy to help you with any questions. Please write us a support request by logging onto your account: https://console.hetzner.cloud/support

Thank you for your understanding.

Kind regards

Hetzner Online
```

This explains that  `docker.io/hetznercloud/cluster-autoscaler` will be removed on 19 November 2024. Meaning, [the default cluster_autoscaler_image variable](  default     = "docker.io/hetznercloud/cluster-autoscaler") will break.

### Kube.tf file

```terraform
n/a
```

### Screenshots

_No response_

### Platform

n/a

### PR DESCRIPTION
**Pull request by BrammyS**
Closes #1505

### CODE REVIEW

**Review by apricote — APPROVED** [review]
PR looks good to me. 1.31.1 includes the fix and otherwise this is a revert of e2fb17ecddbd2ccf1c5e9485227bd1530a3c38a8

**Comment by BrammyS** [comment]
@mysticaltech Any chance you can look at this? The deadline for it is slowly getting closer.

**Comment by mysticaltech** [comment]
Thanks for the heads up @BrammyS, will process it tonight 🙏

**Comment by BrammyS** [comment]
> Thanks for the heads up @BrammyS, will process it tonight 🙏

Bump ;)

**Comment by zeidlos** [comment]
Another Bump. ;)

**Comment by lpellegr** [comment]
Bump Bump

**Review by mysticaltech — APPROVED** [review]
Thanks folks, and appreciate the bumps. Sorry for the delay, was under so much load at work

**Comment by mysticaltech** [comment]
Did an emergency release. Shipped with v2.14.6

**Comment by mysticaltech** [comment]
In the future for any emergency situation, please continue tagging me directly, so that I see the notification. There is also @aleksasiriski that has merge ability. So both of us can do it!

**Pull request merged**
