### PR TITLE
fix: placement group logic redone, including a compatibility mode in …

### LINKED ISSUE #1157: Placement group contains already 10 servers
### Description

My k8s cluster 10 nodes. 

I want add 2 additionals nodes. When apply I got error:
```
│ Error: placement group 211529 contains already 10 servers (service_error)
│ 
│   with module.kube-hetzner.module.agents["1-4-agent-large"].hcloud_server.server,
│   on .terraform/modules/kube-hetzner/modules/host/main.tf line 22, in resource "hcloud_server" "server":
│   22: resource "hcloud_server" "server" {
│ 
```

I try enable placement_group_disable = true

```
  # module.kube-hetzner.module.control_planes["1-0-control-plane-nbg1"].hcloud_server.server will be updated in-place
  ~ resource "hcloud_server" "server" {
        id                         = "35985276"
        name                       = "h-k3s-test-control-plane-nbg1-gdj"
      - placement_group_id         = 192473 -> null
        # (18 unchanged attributes hidden)
    }

Plan: 0 to add, 8 to change, 0 to destroy.
```
but after apply not removed placement group from nodes. New VM added with no placement group. 

May be need params for create placement group for each VM groups like: 

```
    {
      name        = "agent-large",
      server_type = "ccx23",
      location    = "fsn1",
      labels      = [
        "nodetype=core-ccx23"
      ],
      taints      = [],
      count       = 4

    },
```

  

### Kube.tf file

```terraform
module "kube-hetzner" {
  providers = {
    hcloud = hcloud
  }
  hcloud_token = var.hcloud_token != "" ? var.hcloud_token : local.hcloud_token
  source = "kube-hetzner/kube-hetzner/hcloud"
  version = "2.11.4"
  ssh_port = 2222
  ssh_public_key = file("${path.module}/ssh/k8s-hetzner.pub")
  ssh_private_key = file("${path.module}/ssh/k8s-hetzner")

  network_region = "eu-central" # change to `us-east` if location is ash
  network_ipv4_cidr = "10.0.0.0/8"
  cluster_ipv4_cidr = "10.42.0.0/16"

  control_plane_nodepools = [
    {
      name        = "control-plane-fsn1",
      server_type = "cpx21",
      location    = "fsn1",
      labels      = [],
      taints      = [],
      count       = 1

    },
    {
      name        = "control-plane-nbg1",
      server_type = "cpx21",
      location    = "nbg1",
      labels      = [],
      taints      = [],
      count       = 1

    },
  ]

  agent_nodepools = [
    {
      name        = "agent-small",
      server_type = "cpx11",
      location    = "fsn1",
      labels      = [],
      taints      = [],
      count       = 0

    },
    {
      name        = "agent-large",
      server_type = "ccx23",
      location    = "fsn1",
      labels      = [
        "nodetype=core-ccx23"
      ],
      taints      = [],
      count       = 4

    },
    {
      name        = "bots-large",
      server_type = "ccx23",
      location    = "fsn1",
      labels      = [
        "nodetype=bots-node"
      ],
      taints      = [],
      count       = 6
    },
    {
      name        = "agent-xsize",
      server_type = "ccx43",
      location    = "fsn1",
      labels      = [
        "nodetype=core-ccx43"
      ],
      taints      = [],
      count       = 0

    },
    {
      name        = "storage",
      server_type = "ccx23",
      location    = "fsn1",
      labels      = [
        "node.kubernetes.io/server-usage=storage"
      ],
      taints      = [],
      count       = 0
      

    },
    {
      name        = "egress",
      server_type = "cpx11",
      location    = "fsn1",
      labels = [
        "node.kubernetes.io/role=egress"
      ],
      taints = [
        "node.kubernetes.io/role=egress:NoSchedule"
      ],
      floating_ip = true
      count = 0
    },
    {
      name        = "agent-arm-small",
      server_type = "cax11",
      location    = "fsn1",
      labels      = [],
      taints      = [],
      count       = 0
    }
  ]

  load_balancer_type     = "lb11"
  load_balancer_location = "fsn1"

   autoscaler_nodepools = [
     {
       name        = "autoscaled-small"
       server_type = "ccx23"
       location    = "fsn1"
       min_nodes   = 0
       max_nodes   = 0
     },
     {
       name        = "autoscaled-large"
       server_type = "ccx23"
       location    = "fsn1"
       labels      = {
         nodetype: "bots-node"
       }
       min_nodes   = 0
       max_nodes   = 6
     }
   ]

   ingress_controller = "traefik"
   traefik_additional_options = ["--log.level=DEBUG"]
  initial_k3s_channel = "stable"
  cluster_name = "h-k3s-test"

  k3s_registries = <<-EOT
    mirrors:
      eu.gcr.io:
        endpoint:
          - "https://eu.gcr.io"
    configs:
      eu.gcr.io:
        auth:
          username: _json_key
          password: '{
  "type": "service_account",
  "project_id": "asset-management-ci-cd",
  "private_key_id": "a4ccbc8eddbaea86d207ca85bc6482a288035c6d",
  "private_key": "-----BEGIN PRIVATE KEY-----
****
\n-----END PRIVATE KEY-----\n",
  "client_email": "image-puller@asset-management-ci-cd.iam.gserviceaccount.com",
  "client_id": "****",
  "auth_uri": "https://accounts.google.com/o/oauth2/auth",
  "token_uri": "https://oauth2.googleapis.com/token",
  "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
  "client_x509_cert_url": "https://www.googleapis.com/robot/v1/metadata/x509/image-puller%40asset-management-ci-cd.iam.gserviceaccount.com",
  "universe_domain": "googleapis.com"
}'
  EOT

  restrict_outbound_traffic = true

   extra_firewall_rules = [
     {
       description = "Allow out tcp"
       direction       = "out"
       protocol        = "tcp"
       port            = "any"
       source_ips      = [] # Won't be used for this rule
       destination_ips = ["0.0.0.0/0", "::/0"]
     },
     {
       description = "Allow out udp"
       direction       = "out"
       protocol        = "udp"
       port            = "any"
       source_ips      = [] # Won't be used for this rule
       destination_ips = ["0.0.0.0/0", "::/0"]
     }
   ]

   cni_plugin = "cilium"
   placement_group_disable = true
   enable_cert_manager = false
   dns_servers = ["1.1.1.1", "8.8.8.8", "9.9.9.9"]

  cilium_values = <<EOT
ipam:
  mode: kubernetes
k8s:
  requireIPv4PodCIDR: true
kubeProxyReplacement: true
routingMode: native
ipv4NativeRoutingCIDR: "10.0.0.0/8"
endpointRoutes:
  enabled: true
loadBalancer:
  acceleration: native
bpf:
  masquerade: true
socketLB:
  hostNamespaceOnly: true
egressGateway:
  enabled: true
MTU: 1450
EOT

  traefik_values = <<EOT
deployment:
  replicas: 1
globalArguments: []
service:
  enabled: true
  type: LoadBalancer
  annotations:
    "load-balancer.hetzner.cloud/name": "h-k3s-test"
    "load-balancer.hetzner.cloud/use-private-ip": "true"
    "load-balancer.hetzner.cloud/disable-private-ingress": "true"
    "load-balancer.hetzner.cloud/location": "nbg1"
    "load-balancer.hetzner.cloud/type": "lb11"
    "load-balancer.hetzner.cloud/uses-proxyprotocol": "true"

logs:
  general:
    level: DEBUG

ports:
  web:
    redirectTo: websecure

    proxyProtocol:
      trustedIPs:
        - 127.0.0.1/32
        - 10.0.0.0/8
    forwardedHeaders:
      trustedIPs:
        - 127.0.0.1/32
        - 10.0.0.0/8
  websecure:
    proxyProtocol:
      trustedIPs:
        - 127.0.0.1/32
        - 10.0.0.0/8
    forwardedHeaders:
      trustedIPs:
        - 127.0.0.1/32
        - 10.0.0.0/8

tlsOptions: {}
tlsStore: {}
tls:
  secretName: ******

certResolvers:
  letsencrypt:
    email: maxim@test.local
    tlsChallenge: true
    httpChallenge:
      entryPoint: "web"
    storage: /data/acme.json

  EOT

  /*   nginx_values = <<EOT
controller:
  watchIngressWithoutClass: "true"
  kind: "DaemonSet"
  config:
    "use-forwarded-headers": "true"
    "compute-full-forwarded-for": "true"
    "use-proxy-protocol": "true"
  service:
    annotations:
      "load-balancer.hetzner.cloud/name": "h-k3s-test"
      "load-balancer.hetzner.cloud/use-private-ip": "true"
      "load-balancer.hetzner.cloud/disable-private-ingress": "true"
      "load-balancer.hetzner.cloud/location": "nbg1"
      "load-balancer.hetzner.cloud/type": "lb11"
      "load-balancer.hetzner.cloud/uses-proxyprotocol": "true"
  EOT */

  /*   rancher_values = <<EOT
ingress:
  tls:
    source: "rancher"
hostname: "rancher.example.com"
replicas: 1
bootstrapPassword: "supermario"
  EOT */

}

provider "hcloud" {
  token = var.hcloud_token != "" ? var.hcloud_token : local.hcloud_token
}

terraform {
  required_version = ">= 1.3.3"
  required_providers {
    hcloud = {
      source  = "hetznercloud/hcloud"
      version = ">= 1.43.0"
    }
  }
}

output "kubeconfig" {
  value     = module.kube-hetzner.kubeconfig
  sensitive = true
}

output "network_id" {
  value     = module.kube-hetzner.network_id
}
```

### Screenshots

_No response_

### Platform

Linux

### PR DESCRIPTION
**Pull request by valkenburg-prevue-ch**
…order to keep existing clusters compatible with the new logic.

Fixes #1157 .

### CODE REVIEW

**Comment by mysticaltech** [comment]
@valkenburg-prevue-ch will test this tonight. So grateful about this 🙏🙏 💙

**Review by mysticaltech — COMMENTED** [review]
@valkenburg-prevue-ch  Super elegant man! Well done.

Just one clarification I would like to make, and asking your opinion here, we have those limitations in Hetzner:


_In Hetzner Cloud, you can have up to 100 servers per network, up to 50 subnets per project, and each Placement Group can contain up to 10 servers, with a maximum of 50 Placement Groups per project._

Hence, it's pretty fast to reach the limit of max 10 servers per group. Shouldn't we:

1. Enforce a check on the count. I think it's not done now.
2. Impose one uniquely named placement group per nodepool.

What do you think?

**Comment by aleksasiriski** [comment]
Do we really need the compatibility mode? The code seems quite cluttered with it, and I don't see a real benefit.. upgrading the version of module would only result in a different arrangement of nodes via placement groups but nothing breaking would actually happen?

**Review by aleksasiriski — APPROVED** [review]
Do we really need the compatibility mode? The code seems quite cluttered with it, and I don't see a real benefit.. upgrading the version of module would only result in a different arrangement of nodes via placement groups but nothing breaking would actually happen?

I'm fine with merging this and removing the compat_idx in v3 if we want to be proper semver.

**Comment by valkenburg-prevue-ch** [comment]
Yeah, this is exactly what I was hoping, that we only keep the extra compatibility for a limited period, and certainly drop it for v3. I thought that not having it, would lead Terraform to replace nodes, because of the changing placement groups. But Perhaps I'm wrong there?

**Comment by aleksasiriski** [comment]
> Yeah, this is exactly what I was hoping, that we only keep the extra compatibility for a limited period, and certainly drop it for v3. I thought that not having it, would lead Terraform to replace nodes, because of the changing placement groups. But Perhaps I'm wrong there?

I think they won't be replaced, I'll try it on my cluster now to see what really happens.

**Comment by mysticaltech** [comment]
Just don't want to let all of our previous users down, it's important to give them a continued upgrade path especially in the same major version, if removing it does not break the cluster, then of course we should keep the code as simple as possible.

**Comment by mysticaltech** [comment]
In light of #1218 that will come with v3, I think we are good to go. The Hetzner system will give an error if more than 10 nodes are used, it's good enough for now, not a lot of folks use that many nodes. And will add it to the readme. This is an important fix for this major version.

**Pull request merged**
