### PR TITLE
[Critical Bug]: Waiting for MicroOS to become available...

### PR DESCRIPTION
**Pull request by chklauser**
Was `-o IdentitiesOnly yes` instead of `-o IdentitiesOnly=yes`.

This resulted in the error message
```
command-line line 0: no argument after keyword "identitiesonly"
```
when used with `OpenSSH_8.9p1 Ubuntu-3ubuntu0.1, OpenSSL 3.0.2 15 Mar 2022`

I was debugging an issue with cluster creation and manually ran the SSH command that gets used to wait for MicroOS ("Waiting for MicroOS to become available...") when I noticed the error message. I'm not sure if this broke anything because I had also forgotten to load the SSH key in to the agent.

### CODE REVIEW

**Review by aleksasiriski — DISMISSED** [review]

**Comment by aleksasiriski** [comment]
I'm testing this now, THANK YOU!

**Review by otavio — DISMISSED** [review]

**Comment by otavio** [comment]
LGTM.

**Comment by aleksasiriski** [comment]
I'm still experiencing "Waiting for MicroOS to become available..."

@mysticaltech

**Comment by aleksasiriski** [comment]
Using manual commant works without issues and I can ssh into the node, idk why the script hangs and can't ssh into the node

**Comment by aleksasiriski** [comment]
Oh my god... I was running inside a container which doesn't have openssh installed... now it's working.

**Pull request merged**
