### PR TITLE
Allow use of load balancer even if traefik is disabled

### PR DESCRIPTION
**Pull request by otavio**
Fixes: #293.
Signed-off-by: Otavio Salvador <otavio@ossystems.com.br>

### CODE REVIEW

**Comment by mysticaltech** [comment]
Great initiative @otavio, we just need to continue using klipper, that gets activated automatically for single node clusters for instance.

**Comment by otavio** [comment]
Do we need klipper in this case?

**Comment by otavio** [comment]
I wonder as traefik is [creating the load balancer](https://github.com/kube-hetzner/terraform-hcloud-kube-hetzner/blob/master/templates/traefik_config.yaml.tpl#L13) and without it, we would need to make it externally as otherwise, we wouldn't know the IP of it.

**Comment by mysticaltech** [comment]
We need klipper; it's an on-metal lb, which gives all the nodes IPs, not just one. Traffic in the current setup can be used either with the Hetzner LB, or with Klipper. So we would need to maintain klipper functionality.

**Comment by mysticaltech** [comment]
I haven't checked, but normally anything that requests an LB can be used with klipper, but maintaining it tied to traefik as it is now is ok.

**Comment by mysticaltech** [comment]
It's not a lot @otavio, the way I see it, just re-add the checks with `local.using_klipper_lb` that you removed and it should be good to merge.

**Comment by otavio** [comment]
@mysticaltech I did as you asked but it is kinda confusing for me now. How I'd use the load balancer IP this way?

**Comment by mysticaltech** [comment]
@otavio If that seems ok but a lot, you can share your Nginx config, and I will try to make the changes.

**Comment by mysticaltech** [comment]
@otavio I'm taking this on, will merge until here, as it's a valid naming change, and continue adding Nginx on a separate branch. I will tag you in the next PR.

**Pull request merged**
