### PR TITLE
fix lb not being destroy if used as module

### PR DESCRIPTION
**Pull request by strowi**
solves #190 

using kubeconfig.yaml from project-root folder works here.;)

### CODE REVIEW

**Comment by mysticaltech** [comment]
Thanks, @strowi! :)

I was waiting for your first PR to ask you if you wanted to join the team? Basically, you'd be able to get a bit more involved; you will be able to create branches, merge PRs, close issues, and get access to our private Matrix channel.

Not a lot is going on, but I love your ideas and know-how! It would be an honor to add you to our team; what do you say?

**Comment by strowi** [comment]
@mysticaltech thx for the invite, happy to help ;) Although i am not sure how much time i can spend besides work and life.
I just noticed, the MR will break if the module is being used multiple times - it will overwrite the same kubeconfig. It probably should contain the culster-name.

**Comment by mysticaltech** [comment]
Welcome on board @strowi! 🤗 Don't worry; we're all participating on a best-effort basis. Like the spot instances on AWS! 😂

You can join our matrix room here https://matrix.to/#/#kube-hetzner:matrix.org (I will delete this discussion after). Personally, I like the Element-io client, but anything works!

About the MR, I understand something breaks if the module is reused in the same directory, but what do you mean by MR? I agree adding the cluster name, to the kubeconfig filename would be great, like kubeconfig-${cluster-name}.yaml, maybe?!

**Comment by strowi** [comment]
Haha, seems just like my recently updated Xubuntu22.04. Thank you for the warm welcome :) 
How do i join? I am getting a not-invited message from element (using my github-account)?

Yeah i was talking about "MR breaking" because the change also might break existing functionality.
but i just noticed other problems with the module-usage.. It seems the vars inside `module "cluster" { ...}` are not being used. ;/

**Comment by strowi** [comment]
@strowi:matrix.org

**Comment by mysticaltech** [comment]
Just sent you the invite!

**Comment by mysticaltech** [comment]
@strowi Looking forward to the minor tweak to support multiple deploys in the same folder! Adding the cluster name to the kubeconfig filename, for instance.

**Pull request merged**
