### PR TITLE
Outputted `kubeconfig`: Abide to the `cluster_name` module input var

### PR DESCRIPTION
**Pull request by dimisjim**
closes: https://github.com/kube-hetzner/terraform-hcloud-kube-hetzner/issues/357

### CODE REVIEW

**Comment by mysticaltech** [comment]
There are some issues in this PR. Please review my previous comment, and do not change the host, we need that. Instead, add the cluster_name.

Also, kubeconfig_parsed must yamlencode kubeconfig_final, as all versions need to be consistent.

Last but not least, changing "default" that way needs to be tested, as I understand that this is the name of the kube context, and your changes might not work.

Please apply the needed changes, and test it well, and get back to me.

**Comment by mysticaltech** [comment]
@dimisjim Thanks for your changes, that looks fine now. But didn't you want to have `cluster_name` in `kubeconfig_data`? Just add another line for it if you want.

**Comment by dimisjim** [comment]
Indeed it would be nice to have that too in the outputs :+1:

**Review by mysticaltech — APPROVED** [review]
Looking good now, thanks!  🙏 

And I also tried it and checked the naming of the context, user, etc, and it works great. "Default" was just not optimal.
 
ksnip_20221020-151147

**Pull request merged**
