### PR TITLE
Allow the protocol in traefik_additional_ports to be set via a variable

### PR DESCRIPTION
**Pull request by acschm1d**
This PR enhances `traefik_additional_ports` and adds a tweak to the contribution readme section.

`traefik_additional_ports`: `TCP` is always the default protocol. If you want to operate services such as OpenVPN in your cluster, you can only access their daemon via 443 and not via the recommended udp 1194. With my changes, the protocol can be set via a variable in the object list `traefik_additional_ports`.

Since this is my first post to this repo, I noticed when reading your contribution guidelines that there is no `staging` branch. I have changed it to `master`.

### CODE REVIEW

**Comment by aleksasiriski** [comment]
I made the option hardcoded to TCP since Hetzner LB doesn't support UDP as far as I remember, can you test your PR and prove that it's working properly?

Source: https://github.com/hetznercloud/hcloud-cloud-controller-manager/issues/252

**Comment by aleksasiriski** [comment]
Also, please remove the change to the README, it should be a separate PR.

**Comment by acschm1d** [comment]
Interesting, wasn't aware of that restriction. I checked it on the UI in Hetzner Console and indeed, udp is not yet supported:
image

Then I suggest to close this PR and reopen it as soon as it is supported, wdyt @aleksasiriski ?

For the readme change, I separated it into another commit - but I can create a new PR if you want.

**Comment by mysticaltech** [comment]
@aleksasiriski Good catch! I will close the PR. @acschm1d Thanks for the contribution, it's always appreciated and all of us are always reminded that testing is king ;)

**Pull request closed without merging**
