### PR TITLE
fix: undefined ingress key

### PR DESCRIPTION
**Pull request by Silvest89**
Apparently "none" is also possible

### CODE REVIEW

**Comment by Silvest89** [comment]
https://github.com/kube-hetzner/terraform-hcloud-kube-hetzner/pull/1064

**Comment by Silvest89** [comment]
@mysticaltech

**Review by mysticaltech — APPROVED** [review]
Yes,  none is possible. Thanks for the fix. LGTM

**Comment by mysticaltech** [comment]
> @mysticaltech You got a discord url for me?

@Silvest89, welcome, yes of course! https://discord.gg/ZknC3fy7

**Pull request merged**
