### PR TITLE
30m lock-ttl default added for kured_options

### PR DESCRIPTION
**Pull request by asafbennatan**
#1362 
added default value for kured_options.lock-ttl= 30m

### CODE REVIEW

**Review by mysticaltech — APPROVED** [review]
Awesome!

**Comment by mysticaltech** [comment]
@asafbennatan Please if you could add the default values here, it would be better. Also please make sure to use terraform format to make sure it's fixes any spacing or formatting issues automatically. Thanks!

https://github.com/kube-hetzner/terraform-hcloud-kube-hetzner/blob/master/locals.tf#L755-L761

**Comment by asafbennatan** [comment]
done @mysticaltech

**Review by mysticaltech — APPROVED** [review]
Awesome

**Comment by jr-dimedis** [comment]
@mysticaltech , @asafbennatan 

This is a very dangerous change and can lead to a faulty upgrade completely paralyzing the cluster.

It has been made before and was withdrawn for this very reason (see this commit: https://github.com/kube-hetzner/terraform-hcloud-kube-hetzner/commit/d1e5b49a3294eb3c43fa10b5e582a797f7f21dc5). I think the right “fix” here would be to explicitly set the value to 0 and add a comment as to why it should not be changed.

**Comment by mysticaltech** [comment]
@jr-dimedis Appreciate the heads up, you are right, it's dangerous, will revert.

**Comment by asafbennatan** [comment]
hi @jr-dimedis ,
point understood , but the problem is that currently this setup causes sporadic update failures without any reason.
regardless of the default value if not lock-ttl what should be the solution for this ?
this is the solution kured team suggested

**Comment by jr-dimedis** [comment]
Hi @asafbennatan,

I think the solution for you is setting this value just in your local kube-hetzner tf file in the `kured_options` variable.

Changing the default value for _all_ kube-hetzner users is the culprit here :)

**Pull request merged**
