### PR TITLE
etcd snapshots backup to S3 storage

### PR DESCRIPTION
**Pull request by ifeulner**
Hi, this is an initial implementation to support snapshots to S3 storage. 
Done by passing simply the needed args to config.yaml. 
What do you think?

### CODE REVIEW

**Comment by otavio** [comment]
The only missing bit would be the docs about the process to restore the cluster.

**Review by mysticaltech — APPROVED** [review]
@ifeulner LGTM, good work! I believe it's already tested. So good for merging! 🚀 Will do a minor release afterward.

**Comment by mysticaltech** [comment]
@otavio @ifeulner We can just link to https://docs.k3s.io/backup-restore.

**Comment by mysticaltech** [comment]
@ifeulner FYI I added the above link in kube.tf.example.

**Pull request merged**
