### PR TITLE
Custom CIDR

### LINKED ISSUE #572: [Feature-request]: Customize IP-Range of Network
Hello,

Is there a way to set the IP-Range on the network in the kube.tf before the Cluster creation? Currently its 10.0.0.0/8.

We want to add a separatly-managed VM to the Cluster network so the Pods can directly access a service installed on this VM. However, this VM is already attached to a 10.0.0.0/8 network.

Thanks for you help.

### PR DESCRIPTION
**Pull request by mysticaltech**
This is by @aleksasiriski and fixes #572.

### CODE REVIEW

**Comment by mysticaltech** [comment]
@aleksasiriski FYI when doing a test deploy with the following kube.tf:

```terraform
locals {
  hcloud_token = "xxxx"
}

module "kube-hetzner" {
  providers = {
    hcloud = hcloud
  }
  hcloud_token = local.hcloud_token

  source = "../kube-hetzner"

  cluster_name = "test12"

  ssh_public_key  = file("/home/karim/.ssh/id_ed25519.pub")
  ssh_private_key = file("/home/karim/.ssh/id_ed25519")

  network_region = "eu-central"

  control_plane_nodepools = [
    {
      name        = "control-plane-fsn1",
      server_type = "cpx11",
      location    = "fsn1",
      labels      = [],
      taints      = [],
      count       = 1
    },
  ]

  agent_nodepools = [
    {
      name        = "agent-small",
      server_type = "cpx11",
      location    = "fsn1",
      labels      = [],
      taints      = [],
      count       = 1
    },
  ]

  autoscaler_nodepools = [
    {
      name        = "autoscaler"
      server_type = "cpx21" # must be same or better than the control_plane server type (regarding disk size)!
      location    = "fsn1"
      min_nodes   = 1
      max_nodes   = 5
    }
  ]

  automatically_upgrade_k3s = false
  automatically_upgrade_os  = false

  load_balancer_type     = "lb11"
  load_balancer_location = "nbg1"
  cni_plugin             = "calico"
}

provider "hcloud" {
  token = local.hcloud_token
}

terraform {
  required_version = ">= 1.2.0"
  required_providers {
    hcloud = {
      source  = "hetznercloud/hcloud"
      version = ">= 1.35.1"
    }
  }
}

output "kubeconfig" {
  value     = module.kube-hetzner.kubeconfig_file
  sensitive = true
}
```

I get this error:
ksnip_20230215-152330

**Comment by mysticaltech** [comment]
@aleksasiriski To the above error, it just seems that in main`local.network_ipv4_cidr` need to be replaced by `var.network_ipv4_cidr`. That's a good example that shows the importance for testing even for small changes! Hopefully one day we can automate all of it! 🤞

**Comment by aleksasiriski** [comment]
I was away on vacation, will fix this right away and test if it wasn't already fixed

**Comment by aleksasiriski** [comment]
As it seems fixed in #596 we can close this and merge that

**Comment by mysticaltech** [comment]
@aleksasiriski No worries!

**Pull request merged**
