### PR TITLE
Custom CIDR

### PR DESCRIPTION
**Pull request by v-petukhov**
Since [pull request 590](https://github.com/kube-hetzner/terraform-hcloud-kube-hetzner/pull/590) is without any updates. Decided to fix issues opening own pull request

### CODE REVIEW

**Review by aleksasiriski — APPROVED** [review]
Looks good

**Comment by mysticaltech** [comment]
@v-petukhov Thanks for this! You tested and it deploys fine?

**Comment by mysticaltech** [comment]
@v-petukhov Please make sure to run `terraform format` and `terraform validate`, and if you run vscode you can also install the terraform extension that will do that for you automatically.

**Comment by v-petukhov** [comment]
> @v-petukhov Thanks for this! You tested and it deploys fine?

I've tested with two different options — looks ok. I think, that you may also test it to check twice

**Comment by mysticaltech** [comment]
Thanks @v-petukhov, will do one final testing round in the initial commit. For now, merging this one! Thanks again.

**Pull request merged**
