### PR TITLE
Add cilium

### PR DESCRIPTION
**Pull request by PurpleBooth**
Cilium offers some fantastic observability functionality I would like to
take advantage of, along side DNS based filtering in network policies

### CODE REVIEW

**Comment by PurpleBooth** [comment]
Note: I had 5min to do this, so I did. It's the most bare minimum, and really some thought needs to be given to allowing access to the many options Cilium gives you. The ability to enable wireguard, or disable kube proxy from the get go would be of interest. Something is always better than nothing though.

**Comment by mysticaltech** [comment]
@PurpleBooth Awesome! We can propose a sample HelmChartConfig to allow them to do more configurations. This project started with Cilium at the very beginning, so in the git history, we have a few working configs for Cilium.

Anyways, as you said, something is always better than nothing! I will play around with this PR ASAP. I just want to test it and see if we can improve anything (based on previous work).

**Comment by PurpleBooth** [comment]
I got a bit of time upcoming so shout if you want some changes

**Comment by PurpleBooth** [comment]
So I changed the approach a bit, I used the cilium binary, rather than helm crd because I couldn't figure out how to get it to have the right tolerations on the pods it launches, so they were never being scheduled.

The way it's installed basically means it's doing a helm install.

**Comment by mysticaltech** [comment]
Oh man, I know how to fix this non-scheduling issue via helm, just need to pass the right values. Have them all in the git history. Just haven't had time to focus on that. Will try ASAP. 

I prefer like it was before, as the same format we use for everything else, and easier to reconfigure via helm chart config. Also probably easier to update! At least the flow is the same as other addons that we offer.

Will find some time, hopefully tomorrow.

**Comment by PurpleBooth** [comment]
I have a copy of the old way here if it's useful https://github.com/PurpleBooth/terraform-hcloud-kube-hetzner/tree/add-cilium

**Comment by mysticaltech** [comment]
Perfect, definitely 🙏

**Comment by mysticaltech** [comment]
@PurpleBooth Thank you so much for your contributions to this project. We would like to invite you to be a member of our team on Github. It will allow you to create branches (which will make it easier for us to work together on a PR), approve stuff and manage issues if you wish so. Whatever you see fit! ✨

It would also allow you to better influence the direction of this project. We are six people, but most of us do not do much. The current most active members are Phaer and me. I am usually the one to do the releases and was the one who originated the project. It would be an honor to have you be one of us! We all have day jobs, so don't worry; nothing is expected of you; some of our members do not show up for weeks or months! 😁

**Comment by PurpleBooth** [comment]
Lets chat, I tried to login to that room, however I get a "You are not invited to this room.", I am "`@BillieCodes:matrix.org
`" on matrix

**Comment by mysticaltech** [comment]
Hey @PurpleBooth, I just invited you!

**Pull request merged**
