### PR TITLE
feat: taints and labels per autoscaler nodepool

### PR DESCRIPTION
**Pull request by Silvest89**
@mysticaltech it has backwards compatibility now :)

Also added a warning in the docs. Since it depends on an external party ;]

### CODE REVIEW

**Review by mysticaltech — APPROVED** [review]
LGTM 🙏🙏

**Comment by mysticaltech** [comment]
@Silvest89 While trying to upgrade an already created cluster deployed with staging. I get this error:

Screenshot from 2023-10-24 03-09-19

**Comment by mysticaltech** [comment]
I checked at that line, nothing suspicious, only the values yaml, so better you check for yourself what could be going on. Note that I resolved a conflict while merging, but I chose this branch's version.

**Comment by mysticaltech** [comment]
@Silvest89 Confirmed also for non-upgrade scenario, exact same issue.

**Comment by Silvest89** [comment]
Let me check it

**Comment by mysticaltech** [comment]
Thanks! This is my merge conflict correction, so nothing really changed: https://github.com/Silvest89/terraform-hcloud-kube-hetzner/commit/0da340f85903d1ceb2efcc5ce7f9a1644bee52b3

**Pull request merged**
