### PR TITLE
fix: traefik loadbalancer resource name mismatch

### PR DESCRIPTION
**Pull request by me-marcel**
a name mismatch in accordance to the traefik loadbalancer resource name made upgrades from <=v1.4.x to >=v1.5.x impossible

part of: Issue #489

### CODE REVIEW

**Comment by mysticaltech** [comment]
@me-marcel Thank you for this! I understand your concern, but it would break deploys that happened after that change was done. What I suggest it just to point the module in kube.tf, to a local GitHub clone, and do your change manually to be able to upgrade.

Like on like 16 of the screenshot below.

ksnip_20230109-230811

**Comment by me-marcel** [comment]
@mysticxaltech This has already been solved exactly the way you suggested as you have have seen. For reference please take a look at the corresponding issue linked to the PR at https://github.com/kube-hetzner/terraform-hcloud-kube-hetzner/issues/489. 

@captnCC actually suggested to allow a full customization of the resource name by variable within the issue. I just didn't get to modifying the PR just yet. That would provide us with a way to tackle the problem without forcing the users to always keeping a local copy of the module.

Bear in mind that one way or another we will have to implement a permanent solution sooner or later. At least I'd suggest to do since implementing a permanent fix isn't too complicated after all.

**Comment by mysticaltech** [comment]
Great to hear... I also think that allowing for the customization of the LB name is an elegant solution!

**Comment by mysticaltech** [comment]
@me-marcel I am closing this for now, but do not hesitate to push a new PR that adds the ability to set a custom name for the LB, ideally for both Traefik and Ingress-Nginx. Such a feature would be very much welcome! Thanks.

**Pull request closed without merging**
