### PR TITLE
Update hcloud-microos-snapshots.pkr.hcl

### PR DESCRIPTION
**Pull request by wejdross**
replacing default image to working one

### CODE REVIEW

**Comment by mysticaltech** [comment]
@wejdross That really depends on your location, on our end, testing showed that the mirror we have set by default works better. Experience showed us that mirror auto-selection is not as robust as it should be, but good that it worked for you. Where are you located more or less?

**Comment by mysticaltech** [comment]
@kube-hetzner/core Maybe we should try giving the mirror auto-selection a try again? What do you think?

**Review by otavio — APPROVED** [review]
Fixed my error too.

**Comment by wejdross** [comment]
> @wejdross That really depends on your location, on our end, testing showed that the mirror we have set by default works better. Experience showed us that mirror auto-selection is not as robust as it should be, but good that it worked for you. Where are you located more or less?

Its central Switzerland

**Review by aleksasiriski — CHANGES_REQUESTED** [review]
Please change to `https://download.opensuse.org/ports/aarch64/tumbleweed/appliances/openSUSE-MicroOS.aarch64-OpenStack-Cloud.qcow2` for the ARM mirror link as well. After that, it can be merged.

**Comment by mysticaltech** [comment]
Ok, thanks for the info folks, and for confirming this helped you too @octavio. I think there a good chance OpenSUSE on their side are also improving the mirror autoselect, I would agree with this.

**Review by aleksasiriski — APPROVED** [review]

**Comment by aleksasiriski** [comment]
@mysticaltech Should we merge to staging, or directly to master?

**Comment by mysticaltech** [comment]
Thanks @wejdross!! And @aleksasiriski  🚀

**Comment by mysticaltech** [comment]
Just released in v2.1.3 !

**Pull request merged**
