### PR TITLE
feat: add wireguard option

### PR DESCRIPTION
**Pull request by valkenburg-prevue-ch**
I chose not to make this an optional thing, avoiding adding variables. Only merge this branch if tests show that it is a good idea. Otherwise modify the code to make wireguard optional. See https://github.com/kube-hetzner/terraform-hcloud-kube-hetzner/issues/527

I do not know all the arguments for and against making this standard, so I am marking this MR as draft and hope to see some discussion about it.

### CODE REVIEW

**Comment by aleksasiriski** [comment]
This should be optional, Hetzner networks are isolated and if they're used only within the same location (eu-cental for example) I don't think there would be any security risks, but maybe I'm wrong about that? I'll send an email to Hetzner..

**Comment by aleksasiriski** [comment]
> I wonder if there is really any noticeable performance loss.

It can be the default but should be optional, for some edge cases..

**Comment by valkenburg-prevue-ch** [comment]
Yes, I think your absolutely right. Let's make it optional with a good default. Perhaps default false for a little while and then switch to true after we find no issues for a while?

**Comment by valkenburg-prevue-ch** [comment]
I may do it tomorrow morning, but feel free to beat me to it!

**Comment by aleksasiriski** [comment]
> I may do it tomorrow morning, but feel free to beat me to it!

I'm on it, will be done in a couple of minutes...

**Comment by aleksasiriski** [comment]
> I may do it tomorrow morning, but feel free to beat me to it!

It's done.. but I don't know if this:
```terraform
cni_k3s_settings = {
    "flannel" = {
      disable-network-policy = var.disable_network_policy
      flannel-backend        = var.encrypt_kubernetes_api ? "wireguard-native" : "vxlan"
    }
    "calico" = {
      disable-network-policy = true
      flannel-backend        = "none"
    }
    "cilium" = {
      disable-network-policy = true
      flannel-backend        = "none"
    }
  }
```

should be changed to this:
```terraform
cni_k3s_settings = {
    "flannel" = {
      disable-network-policy = var.disable_network_policy
      flannel-backend        = var.encrypt_kubernetes_api ? "wireguard-native" : "vxlan"
    }
    "calico" = {
      disable-network-policy = true
      flannel-backend        = var.encrypt_kubernetes_api ? "wireguard-native" : "none"
    }
    "cilium" = {
      disable-network-policy = true
      flannel-backend        = var.encrypt_kubernetes_api ? "wireguard-native" : "none"
    }
  }
```

**Comment by mysticaltech** [comment]
@valkenburg-prevue-ch Great, initiative! It adequately addresses #527.

Also, I do agree with both of you that it needs to be optional. @aleksasiriski The first option is the right one, as calico and cilium get configured for this differently, folks can just use the *_values variable to do so.

**Comment by aleksasiriski** [comment]
Shouldn't we add this encryption to calico and cilium as well?

**Comment by otavio** [comment]
> > Please do. I'm using cillium as flannel had intermittent network failures. As I plan to add bare metal machine in the cluster for ci use the wireguard is required.

**Review by ifeulner — CHANGES_REQUESTED** [review]
It's not the api but the whole network communication between the nodes and pods. So the name of the variable is a little bit misleading. Also it is this way only for flannel. As soon as you change the CNI this setting is not valid anymore.

**Comment by aleksasiriski** [comment]
> It's not the api but the whole network communication between the nodes and pods. So the name of the variable is a little bit misleading. Also it is this way only for flannel. As soon as you change the CNI this setting is not valid anymore.

How should we rename it? `encrypted_network`? I'll look into enabling it for calico and cilium

**Comment by valkenburg-prevue-ch** [comment]
How about `enable_wireguard`, and a comment in kube.ft.example explaining that right now this is only relevant when using flannel?

**Comment by aleksasiriski** [comment]
> @aleksasiriski Definitely! But, the reason why I am more relaxed about this is that they have the `*_values` variable to add it if they want to. It just needs some reading of the helm values yaml.
> 
> However, why not make this easier for them, and piggyback on the `encrypt_kubernetes_api` boolean too! 🚀

There literally is no `calico_values`, only cilium, I added it my PR. Wouldn't it better to switch from patching the manifest to calico's helm chart?

**Comment by aleksasiriski** [comment]
> I wonder if there is really any noticeable performance loss.

As I read in cilium's docs, when wireguard is enabled EVERY node makes a tunnel to EVERY other node. If you had 20 nodes that would mean n(n-1)/2 where n=20 -> 190 wireguard tunnels.

**Comment by mysticaltech** [comment]
> > @aleksasiriski Definitely! But, the reason why I am more relaxed about this is that they have the `*_values` variable to add it if they want to. It just needs some reading of the helm values yaml.
> > However, why not make this easier for them, and piggyback on the `encrypt_kubernetes_api` boolean too! rocket
> 
> There literally is no `calico_values`, only cilium, I added it my [PR](https://github.com/kube-hetzner/terraform-hcloud-kube-hetzner/pull/536). Wouldn't it better to switch from patching the manifest to calico's helm chart?

Oh yes, had forgotten about that. The reason for that is that I actually did not find the calico helm chart, if you do find it, please let's more to helm!

**Comment by aleksasiriski** [comment]
> > > @aleksasiriski Definitely! But, the reason why I am more relaxed about this is that they have the `*_values` variable to add it if they want to. It just needs some reading of the helm values yaml.
> > > However, why not make this easier for them, and piggyback on the `encrypt_kubernetes_api` boolean too! rocket
> > 
> > 
> > There literally is no `calico_values`, only cilium, I added it my [PR](https://github.com/kube-hetzner/terraform-hcloud-kube-hetzner/pull/536). Wouldn't it better to switch from patching the manifest to calico's helm chart?
> 
> Oh yes, had forgotten about that. The reason for that is that I actually did not find the calico helm chart, if you do find it, please let's move to helm!

I found [this](https://projectcalico.docs.tigera.io/getting-started/kubernetes/helm), but when running `helm show values` it's quite poor compared to cilium for example.

**Comment by mysticaltech** [comment]
Great! @aleksasiriski If it supports wireguard, and a few other basic options, I think it's better than the current manifest approach!

**Comment by aleksasiriski** [comment]
> Great! @aleksasiriski If it supports wireguard, and a few other basic options, I think it's better than the current manifest approach!

I'll add it to my PR then

**Comment by aleksasiriski** [comment]
> Great! @aleksasiriski If it supports wireguard, and a few other basic options, I think it's better than the current manifest approach!

This is all that helm show values outputs:

```yaml
imagePullSecrets: {}

installation:
  enabled: true
  kubernetesProvider: ""

apiServer:
  enabled: true

certs:
  node:
    key:
    cert:
    commonName:
  typha:
    key:
    cert:
    commonName:
    caBundle:

# Resource requests and limits for the tigera/operator pod.
resources: {}

# Tolerations for the tigera/operator pod.
tolerations:
- effect: NoExecute
  operator: Exists
- effect: NoSchedule
  operator: Exists

# NodeSelector for the tigera/operator pod.
nodeSelector:
  kubernetes.io/os: linux

# Custom annotations for the tigera/operator pod.
podAnnotations: {}

# Custom labels for the tigera/operator pod.
podLabels: {}

# Image and registry configuration for the tigera/operator pod.
tigeraOperator:
  image: tigera/operator
  version: v1.29.0
  registry: quay.io
calicoctl:
  image: docker.io/calico/ctl
  tag: v3.25.0
```

**Comment by mysticaltech** [comment]
@aleksasiriski There is also this page, that links to a helm chart, I do not know if it's the same, but it seems to be the main one. Also, there is the Tigera operator, maybe that is needed to deploy/manage Calico. https://github.com/projectcalico/calico/blob/master/calico/getting-started/kubernetes/helm.md

**Comment by ifeulner** [comment]
As long as we don't know for sure what a good implementation would mean for other CNI providers we should just support what we know that it works. 
I used flannel with wg without any problems. If anyone has real experiences with Cilium et al. then we could support a setting that really works. Otherwise we should wait until someone is coming up with a setting. 
I am even asking if we need additional support here for Flannel as it obviously already works with the current configuration options (by adjusting two variables)

**Comment by mysticaltech** [comment]
Yes, that makes a lot of sense @ifeulner!

However, if @aleksasiriski can make Calico work, then why not, it seems like a low-hanging fruit!

**Comment by mysticaltech** [comment]
I mean, we have it working already, so it's just a push to transition to a helm chart if possible. It's something I attempted myself in the past.

**Comment by mysticaltech** [comment]
Alright folks, this looks good to me and would properly add wireguard encryption to our cluster! We need not overcomplicate it with mingling concerns about how calico is deployed. 

So let's test this and merge! I will do a test run ASAP.

**Comment by mysticaltech** [comment]
Ok merging to the staging branch and will do a round of testing before releasing. Great work @valkenburg-prevue-ch @aleksasiriski ! 🚀

**Pull request merged**
