### PR TITLE
adding postinstall_exec to hook restore commands

### PR DESCRIPTION
**Pull request by schlichtanders**
After two intensive weeks with all kinds of trial and errors with cluster restoration from etcd backup, actually only this postinstall_exec hook is needed to make it work.

### CODE REVIEW

**Review by mysticaltech — APPROVED** [review]
Looking good! An example of how to use it, with or without the greatest context of restauration would be awesome. We have the examples section in the readme and/or the examples folder, for such demos.

**Comment by schlichtanders** [comment]
good idea! I have a longer train ride today and will add in then.

**Comment by schlichtanders** [comment]
I added a documentation about how to do the restoration

unfortunately, I needed to revert one change recently done, because it broke my cluster. See https://github.com/kube-hetzner/terraform-hcloud-kube-hetzner/issues/970

**Comment by schlichtanders** [comment]
according to this https://github.com/kube-hetzner/terraform-hcloud-kube-hetzner/issues/970#issuecomment-1710221565 it seems indeed best to comment the cloud-init command as currently done in this pullrequest

**Comment by mysticaltech** [comment]
@schlichtanders  This line was not needed, I don't know why I accepted the PR in the first place, it looked like a good idea, but we already do implicit checks. So will merge this now and remove it completely. And wonderful job on the restore example, love it! 🥳 🙏

**Review by mysticaltech — APPROVED** [review]
Let's go  🚀

**Comment by mysticaltech** [comment]
Awesome, thanks @schlichtanders. Keep up the good work, amazing contributions to this project.

**Pull request merged**
