### PR TITLE
#160 Install open-iscsi and Longhorn

### PR DESCRIPTION
**Pull request by karbowiak**
ref: #160

This installs open-iscsi and Longhorn using Helmfile.

Not sure this is the optimal way to do it - but it does work 😅

### CODE REVIEW

**Comment by skriems** [comment]
cool :) I think I get the idea that you use `transactional-update` for starting the deamon, as this also create a snapshopt, right? I wonder if that's necessary 🤔 

With `defaultClass: true` you're setting longhorn as the default StorageClass, right? I wonder if its possible if longhorn can be combined with the hcloud-storage class. Haven't had time to look into that. On the other hand I assume that with longhorn you _want_ to have the volumes on the nodes and an additional backup strategy should push data to hetzner volumes, maybe... 🤔

**Comment by karbowiak** [comment]
@skriems 

Afaik just doing `systemctl enable --now iscsid` will just enable it for now, after the next reboot it'll be gone - hence the transactional update :)

as for `defaultClass: true` it's just what i use myself, i noticed after i made the pull request that hcloud is also setting itself as default 😅 

So by default it'll most likely end up using hcloud since it comes first in the alphabet.
As for backing up Longhorn, that has to happen to an S3 bucket - that's how it's own internal backup solution works.

As for single node clusters, it wouldn't fail - it'd just still try and keep 2 volumes around 😂 
As for setting it to the X amount of worker nodes added, that could work - but you'd end up with very little usable space, longhorn should be smart enough to move a volume over to the node that requires it if it doesn't have it there already

**Comment by mysticaltech** [comment]
@karbowiak Thanks! There are many good things in this PR; I like how you think. However, a few things. 

It needs to be fully optional, with a variable flag to determine if longhorn is used or not.

Also, the whole interaction with hcloud needs to be clarified, and the different major use cases need to be exposed with a flag. 

One of those use cases would be either hcloud or longhorn (mutual exclusion), in which case the Hetzner CSI needs to never get installed (so its installation must be if longhorn is false, for instance).

Last but not least, please retarget this PR to the "staging" branch, so we can test it out. We try to keep the master in sync with the latest release. So closing for now while you re-submit it to the "staging" branch, and from there, we can make the improvements needed before we merge.

**Comment by mysticaltech** [comment]
As for the systemctl enable --now, am almost sure it does not need transactional updates as @skriems mentioned, please double check!

**Comment by skriems** [comment]
@karbowiak I checked the docs and in fact an `enable --now` does both, _enable_ (start the deamon after reboot) and _start_ a given deamon. So I think since nothing is really installed we can omit the transactional-update :)

I you still working on this?

**Pull request closed without merging**
