### PR TITLE
Rancher addon

### PR DESCRIPTION
**Pull request by mysticaltech**
This adds both cert-manager and rancher!

ksnip_20220504-214126

### CODE REVIEW

**Comment by strowi** [comment]
Nice work, can't test it atm though.
Just a small thing: Will `number_control_plane_nodes` somehow override the `allow_scheduling_on_control_plane`, or is it too early and i need more coffee first? If so it might me worth mentioning. ;)

**Comment by mysticaltech** [comment]
@strowi Thanks for diving deep into the code! `number_control_plane_nodes` is just a count, and `allow_scheduling_on_control_plane` is a boolean turned on automatically in the case of single-node clusters to allow for scheduling of payloads on the control plane(s). So both are not related! So either it was too early, you needed coffee, or I'm missing your point! 😂

**Comment by strowi** [comment]
> `allow_scheduling_on_control_plane`  is a boolean turned on automatically in the case of single-node clusters 
That's what i meant to ask or what confused me- ;) 
`number_control_plane_nodes` has nothing to do with the `control_plane_nodepools`-count.
I thought about the recommended 3-node Rancher-HA-Cluster (control-plane on all 3 nodes) as per the [rancher-docs](https://rancher.com/docs/rancher/v2.5/en/installation/resources/k8s-tutorials/how-ha-works/#recommended-architecture), which have the rancher-workload running on control-nodes.

**Comment by mysticaltech** [comment]
Ah yes, I understand. Then all good huh, no change needed? I thought it would make sense to have Rancher on CP nodes.

**Comment by strowi** [comment]
I would just leave it as is.
We never deployed the helm-chart on a single node, since it is equivalent to `docker run rancher...`.

For HA you want 3 control nodes for the rancher-cluster itself (because of etcd + quorum) but don't really have any load on it. So it makes sense to run the rancher-cluster on the same cp nodes. I don't really see a point in adding extra-workers for the rancher-ui.

**Comment by mysticaltech** [comment]
Makes sense! Thanks for clarifying 🙏

**Comment by strowi** [comment]
@mysticaltech regarding the rancher-addon - i "had" to implement a code-only approach to importing the downstream-clusters into the rancher-ui last couple of days. 
It works by using the offical rancher/rancher2 provider with access + secret-key of a user and doesn't need logging into the rancher-ui (after getting the credentials of course). 
It has also the advantage, that it would be possible to install additional rancher-apps (like monitoring etc..) via terraform in one go.  If this seems like a good idea i can open a MR.

**Comment by mysticaltech** [comment]
Definitely, please do! 🙏✨

**Pull request merged**
