### PR TITLE
readme: single node setup

### PR DESCRIPTION
**Pull request by panakour**
related to: https://github.com/kube-hetzner/terraform-hcloud-kube-hetzner/issues/338 and https://github.com/kube-hetzner/terraform-hcloud-kube-hetzner/issues/311

### CODE REVIEW

**Comment by captnCC** [comment]
Looks good, thank you!

**Comment by phaer** [comment]
Thanks for caring about documentation, but I am not sure whether we just want to recommend using an older version to "prevent some errors". We should rather get a better understanding of the bug, open it upstream and link the issue in the README so people know when it applies.

**Comment by captnCC** [comment]
There is already an upstream issue on the ccm repo: hetznercloud/hcloud-cloud-controller-manager#282
But yes the upstream issue and #311 should be mentioned in the read me as it is already done in the `kube.tf.example`

**Comment by mysticaltech** [comment]
Thanks, folks! @phaer You are right; we will delete that detail as soon as the issue is fixed; currently looking into it.

**Pull request merged**
