### PR TITLE
Labels for everything

### PR DESCRIPTION
**Pull request by captnCC**
This adds labels to all resources provisioned by terraform. The `cleanup.sh` is a little helper to remove all resources of a cluster if terraform has gone south (only limitation for now are CSI volumes and autoscaler nodes)

### CODE REVIEW

**Review by mysticaltech — APPROVED** [review]
Perfect. It's an extra safety net, well done!

**Comment by mysticaltech** [comment]
@captnCC Next time, merge to staging first, so that we keep master in sync with the release. What I have been doing recently is merge PRs into staging, and then when we have a few important ones, merge staging to master and do a release. 

But all is good, no worries! For now, let's merge all the open PRs that are reviewed to master and do a quick release. For new ones, we can start targeting the staging branch again, after updating it.

**Comment by captnCC** [comment]
@mysticaltech Sorry, I was just going with my habits, but I will keep it in mind for the next ones!

**Comment by mysticaltech** [comment]
No worries, I haven't been clear on that either. And thanks a lot for the help and great contributions to this project. Really happy to have you on the team!

**Pull request merged**
