### PR TITLE
Update terraform provider versions

### PR DESCRIPTION
**Pull request by RelativeSure**

### CODE REVIEW

**Comment by RelativeSure** [comment]
image

**Comment by mysticaltech** [comment]
@RelativeSure Thanks for this, super important indeed. Please could you also check kube.tf.example, I believe it has some versions to upgrade in there too.

**Review by mysticaltech — APPROVED** [review]
LGTM

**Review by aleksasiriski — APPROVED** [review]

**Review by aleksasiriski — CHANGES_REQUESTED** [review]
Please remove your terraform lock state

**Comment by mysticaltech** [comment]
@RelativeSure , about the terraform lock file, @aleksasiriski has a point, I understand the recommendation from terraform, however this does not apply to that repo that is just a module. In the place where you use the kube-hetzner module, you can commit that state indeed.

**Review by aleksasiriski — APPROVED** [review]

**Pull request merged**
